// @ts-nocheck
import { ArtifactValidationError, deriveExecutionStatus, parseBacklog, topologicalOrder } from './backlog.mjs';

export { ArtifactValidationError as GraphValidationError };

function escapeMermaid(text) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const CLASSES = [
  '  classDef completed fill:#dcfce7,stroke:#16a34a,color:#14532d;',
  '  classDef in_progress fill:#dbeafe,stroke:#2563eb,color:#1e3a8a;',
  '  classDef eligible fill:#fef3c7,stroke:#d97706,color:#78350f;',
  '  classDef blocked fill:#fee2e2,stroke:#dc2626,color:#7f1d1d;'
];

const LINK_STYLES = {
  completed: 'stroke:#16a34a,stroke-width:2px',
  in_progress: 'stroke:#2563eb,stroke-width:3px',
  eligible: 'stroke:#d97706,stroke-width:2px,stroke-dasharray:6 4',
  blocked: 'stroke:#dc2626,stroke-width:2px,stroke-dasharray:2 3'
};

export function generateGraphMarkdown(backlogText) {
  const { work_items: items } = typeof backlogText === 'string' ? parseBacklog(backlogText) : backlogText;
  const ordered = topologicalOrder(items);
  const byId = new Map(items.map((item) => [item.id, item]));
  const statuses = new Map(items.map((item) => [item.id, item.state ?? deriveExecutionStatus(item, byId).status]));
  const edges = ordered.flatMap((source) =>
    ordered
      .filter((target) => target.depends_on.includes(source.id))
      .map((target) => ({ source: source.id, target: target.id }))
  );
  const lines = [
    '# Work-item dependency graph',
    '',
    '> Derived from canonical work-items. Do not edit this file manually.',
    '',
    '## Status',
    '',
    '- Ã°Å¸Å¸Â© **Completed** Ã¢â‚¬â€ accepted work.',
    '- Ã°Å¸Å¸Â¦ **In Progress** Ã¢â‚¬â€ currently executing.',
    '- Ã°Å¸Å¸Â¨ **Eligible** Ã¢â‚¬â€ pending work with dependencies and blockers satisfied.',
    '- Ã°Å¸Å¸Â¥ **Blocked** Ã¢â‚¬â€ pending work with an incomplete dependency or unresolved blocker.',
    '',
    '```mermaid',
    "%%{init: {'flowchart': {'curve': 'linear', 'nodeSpacing': 32, 'rankSpacing': 54}} }%%",
    'flowchart TD'
  ];
  for (const item of ordered) lines.push(`  ${item.id}["${escapeMermaid(item.id)}<br/>${escapeMermaid(item.title)}"]`);
  lines.push('');
  for (const edge of edges) lines.push(`  ${edge.source} --> ${edge.target}`);
  lines.push('');
  edges.forEach((edge, index) => lines.push(`  linkStyle ${index} ${LINK_STYLES[statuses.get(edge.source)]};`));
  lines.push('', ...CLASSES);
  for (const status of ['completed', 'in_progress', 'eligible', 'blocked']) {
    const ids = ordered.filter((item) => statuses.get(item.id) === status).map((item) => item.id);
    if (ids.length) lines.push(`  class ${ids.join(',')} ${status};`);
  }
  lines.push(
    '```',
    '',
    'Dependency arrows are authoritative for execution ordering. Flow executes one mutating task at a time; independent read-only research or review may run in parallel.',
    ''
  );
  return lines.join('\n');
}
