import fs from 'node:fs';
import path from 'node:path';
import { info } from '../shared/cli-io.mjs';
import { projectRoot } from '../shared/project-path.mjs';
import { ArtifactValidationError, deriveExecutionStatus, parseBacklog, topologicalOrder } from '../artifacts/backlog.mjs';

export { ArtifactValidationError as GraphValidationError };

function escapeMermaid(text) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const CLASSES = [
  '  classDef completed fill:#dcfce7,stroke:#16a34a,color:#14532d;',
  '  classDef in_progress fill:#dbeafe,stroke:#2563eb,color:#1e3a8a;',
  '  classDef ready fill:#fef3c7,stroke:#d97706,color:#78350f;',
  '  classDef blocked fill:#fee2e2,stroke:#dc2626,color:#7f1d1d;'
];

export function generateGraphMarkdown(backlogText) {
  const { work_items: items } = parseBacklog(backlogText);
  const ordered = topologicalOrder(items);
  const byId = new Map(items.map((item) => [item.id, item]));
  const statuses = new Map(items.map((item) => [item.id, deriveExecutionStatus(item, byId).status]));
  const edges = ordered.flatMap((source) =>
    ordered.filter((target) => target.depends_on.includes(source.id)).map((target) => ({ source: source.id, target: target.id }))
  );
  const lines = [
    '# Work-item dependency graph', '',
    '> Derived from `../backlog.yaml`. Do not edit this file manually.', '',
    '## Status', '',
    '- **Completed** — accepted work.',
    '- **In Progress** — currently executing.',
    '- **Ready** — pending work with all dependencies satisfied.',
    '- **Blocked** — pending work with at least one incomplete dependency or explicit external blocker.', '',
    '```mermaid',
    "%%{init: {'flowchart': {'curve': 'linear', 'nodeSpacing': 32, 'rankSpacing': 54}} }%%",
    'flowchart TD'
  ];
  for (const item of ordered) lines.push(`  ${item.id}["${escapeMermaid(item.id)}<br/>${escapeMermaid(item.title)}"]`);
  lines.push('');
  for (const edge of edges) lines.push(`  ${edge.source} --> ${edge.target}`);
  lines.push('', ...CLASSES);
  for (const status of ['completed', 'in_progress', 'ready', 'blocked']) {
    const ids = ordered.filter((item) => statuses.get(item.id) === status).map((item) => item.id);
    if (ids.length) lines.push(`  class ${ids.join(',')} ${status};`);
  }
  lines.push('```', '', 'Dependency arrows are authoritative for execution ordering. Work items in the same rank may execute in parallel only when their files/contracts do not conflict; mutating tasks additionally require isolated Git worktrees.', '');
  return lines.join('\n');
}

export function writeGraph(root) {
  const backlogPath = path.join(root, '.flow', 'backlog.yaml');
  if (!fs.existsSync(backlogPath)) throw new ArtifactValidationError(`Backlog not found: ${backlogPath}`);
  const graphPath = path.join(root, '.flow', 'docs', 'graph.md');
  fs.mkdirSync(path.dirname(graphPath), { recursive: true });
  const markdown = generateGraphMarkdown(fs.readFileSync(backlogPath, 'utf8'));
  const temporaryPath = `${graphPath}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(temporaryPath, markdown, 'utf8');
  fs.renameSync(temporaryPath, graphPath);
  return { graphPath, markdown };
}

export function runGraph({ args }) {
  const result = writeGraph(projectRoot(args));
  info(`Generated ${result.graphPath}`);
}
